### ISSUE TITLE
The `--insecure` argument is present by default, even though documentation says otherwise

### ISSUE THREAD

**Issue by ridercz** [imperugo/HttpRequestToCurl#6]
If `ToCurlAsync` method is called without parameters, the `--insecure` argument is present in generated output. Documentation (README) says

> If you want to use the --insecure you could do it with the specific parameter.

which is therefore not true. Either code or documentation should be updated.

**Comment by imperugo** [comment]
Hi @ridercz 
thanks for the feedback. Just pushed the the fix that includes the right default value for insecure flag. 
Take a look
