### ISSUE TITLE
Generated command is not runnable

### ISSUE THREAD

**Issue by ridercz** [imperugo/HttpRequestToCurl#7]
The command generated by the `ToCurlAsync` method actually cannot be run anywhere, as far as I know.

* First, the command is generated as multi-line, without escape characters. There should be option to use escapes either for cmd.exe (`^`), PowerShell (`` ` ``) or Bash (`\`).
* Second, it uses 'single quotes' to enclose values which is illegal in cmd.exe, which expects "double quotes" in its default settings.
* Third, for PowerShell, which is now default command line on Windows, does recognize `curl` as alias for `Invoke-WebRequest`, with completely different argument set. To invoke real curl, `curl.exe` has to be used, which would not work in Bash.

## Proposed solution

Include (preferably global) configuration option as to which code should be generated. As it has to be compatible either with cmd.exe (the legacy Windows command line), PowerShell or Bash.

**Comment by imperugo** [comment]
I just pushed a version that includes the missin `\`.

I just use it to import into Postman and there are not needed (see here my post https://imperugo.medium.com/log-curl-from-your-http-request-797562a14ad9).

Now it works also from terminal.
Take a look and let me know

.u

**Comment by imperugo** [comment]
Going to cose it.
Please feel free to open it again if you still have the problem with the new version

**Comment by ridercz** [comment]
It only fixes part of the problem. Now the command is runnable, but only in Bash, nowhere else. I think the best solution would be to create injected configuration object, which would hold information about the platform (Bash, CMD or PowerShell) and then it will create command with the right command (`curl` or `curl.exe`), right quotes and right escapes for the given platform.

**Comment by imperugo** [comment]
@ridercz could you elaborate better with an example or a PR?

**Comment by ridercz** [comment]
Okay, added a PR #8

**Comment by imperugo** [comment]
Thanks @ridercz 
I've merged your PR and added the support for the http2 protocol.
